run:
  timeout: 5m
  tests: true
linters:
  enable:
    - govet
    - staticcheck
    - revive
    - gofmt
    - goimports
    - gocritic
    - errcheck
    - ineffassign
    - gosimple
issues:
  exclude-use-default: false
